// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetIsExecuting():Promise<boolean>;

export function ListProjects():Promise<Array<backend.ProjectSummary>>;

export function LoadLastFile():Promise<backend.FlowData>;

export function LoadProject(arg1:string):Promise<backend.FlowData>;

export function SaveFile(arg1:backend.FlowData,arg2:string,arg3:string):Promise<string>;

export function StartExecution(arg1:string):Promise<void>;

export function StopExecution():Promise<void>;
