import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import svelteConfig from './svelte.config.js';

export default defineConfig(
	globalIgnores([
		'.svelte-kit/',
		'build/',
		// `npm run coverage` output: the v8 report and its bundled HTML viewer.
		'coverage/',
		'dist/',
		// Generated by `wails3 generate bindings` from the Go side. Regenerated
		// wholesale, so anything fixed here is lost on the next build.
		'src/lib/bindings/',
		'**/*.timestamp-*.mjs'
	]),

	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,

	// Both of these turn rules *off*, so they have to stay last among the shared
	// configs: `prettier` drops the core formatting rules, and the Svelte one
	// drops the template-formatting rules that would otherwise fight the
	// formatter over indentation inside markup.
	prettier,
	svelte.configs.prettier,

	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					// Naming a prop only to keep it out of `...rest` is a real use of
					// it - NodeWrapper destructures `type` for exactly that reason, so
					// that a caller's `type="Delay"` does not get spread onto a `<div>`.
					ignoreRestSiblings: true,
					// The usual escape hatch for a binding that must exist but is not read.
					varsIgnorePattern: '^_',
					argsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_'
				}
			]
		}
	},

	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				parser: ts.parser,
				svelteConfig,
				extraFileExtensions: ['.svelte']
			}
		},
		rules: {
			// Beyond recommended: pushes the remaining createEventDispatcher sites
			// towards callback props.
			'svelte/require-event-prefix': 'warn'

			// `svelte/prefer-destructured-store-props` was tried here and removed. It
			// predates runes and reads a rune namespace as store property access, so
			// it reports `$effect.root(...)` as "destructure root from $effect" and
			// `$state.snapshot(...)` as "destructure snapshot from $state". Every hit
			// on this codebase was one of those.
		}
	},

	// Type-aware rules on plain .ts only. The Svelte parser is a singleton and
	// reports positions inside a virtual shim, which makes type-aware findings in
	// components hard to act on - and svelte-check already type-checks those.
	{
		files: ['src/**/*.ts'],
		extends: [ts.configs.recommendedTypeChecked],
		languageOptions: {
			parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname }
		}
	},

	// Tests reach into internals and hand deliberately wrong values to functions
	// to prove they are rejected, which is the one place `any` is the point.
	{
		files: ['src/**/*.test.ts', 'src/lib/test/**'],
		rules: {
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-argument': 'off',

			// Off in tests because it is wrong here, not merely noisy. Testing
			// Library types `getByLabelText` as returning `HTMLElement`, and the
			// tests narrow that to `HTMLInputElement` / `HTMLSelectElement` to reach
			// `.value`, `.maxLength` and `.options`. This rule calls those casts
			// unnecessary and `--fix` strips them, which breaks the build: five
			// "Property 'value' does not exist on type 'HTMLElement'" errors from
			// svelte-check on the very next run. ESLint's projectService and
			// svelte-check resolve that generic differently, and svelte-check is the
			// one that gates CI, so it wins.
			'@typescript-eslint/no-unnecessary-type-assertion': 'off'
		}
	}
);
