// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Update the App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetIsExecuting returns the current execution state.
 */
export function GetIsExecuting(): $CancellablePromise<boolean> {
    return $Call.ByID(835063317);
}

/**
 * ListProjects enumerates the saved macros in the app data directory.
 * 
 * A file that is not readable, is not valid JSON, or is JSON but not a flow is
 * skipped and logged: one stray file in the data directory must not take the
 * whole listing down with it.
 */
export function ListProjects(): $CancellablePromise<$models.ProjectSummary[] | null> {
    return $Call.ByID(2522493591);
}

/**
 * LoadLastFile loads the macro the workspace had open when it was last used,
 * returning nil without an error when there is none to load.
 * 
 * The macro is recorded in the settings file as an id, not a path, so this is
 * LoadProject by another name: the id goes through the same projectPath
 * validation, which is what keeps a hand-edited config.json from naming a file
 * outside the data directory. An id that fails it is treated as no last macro
 * at all - the app opens on an empty canvas rather than refusing to start over
 * a setting.
 * 
 * "Nothing to load" also covers the macro having been deleted since. The
 * remaining errors are a file that is there but unreadable or not a flow, which
 * the user should be told about rather than have silently swallowed.
 */
export function LoadLastFile(): $CancellablePromise<$models.FlowData | null> {
    return $Call.ByID(2612448559);
}

/**
 * LoadProject loads a single saved macro by the id ListProjects handed out.
 * 
 * The id arrives from the frontend and is turned into a path, so it is
 * validated as a bare filename first - see sanitizeProjectID.
 */
export function LoadProject(id: string): $CancellablePromise<$models.FlowData | null> {
    return $Call.ByID(76246062, id);
}

/**
 * RunMacro loads a saved macro by id and runs it, without the caller having to
 * hold the graph. It is what the tray menu and the global hotkeys use: neither
 * has a frontend to get the flowchart from, and both have to work with the
 * window closed.
 * 
 * It is bound to the frontend as well, so the projects list can run a macro
 * without opening it in the workspace first.
 * 
 * **It is a toggle.** A run in progress is stopped and nothing is started; only
 * an idle app starts one. This is AutoHotkey's canonical `Toggle := !Toggle`,
 * expressed with the context cancellation this app already has instead of a
 * shared flag, and it is what makes an endless loop a usable macro rather than
 * a trap: with the iteration budget gone, the hotkey the user pressed to start
 * a loop is the way out of it. The re-entrancy hazard those threads keep
 * hitting - a second press landing inside the first press's still-running loop
 * - is commit 33797cb's bug, and the runner's generation token is what stays to
 * make this safe.
 * 
 * **startFlow deliberately keeps its refusal**, and the toggle lives only here.
 * The two entry points want different answers. This one is a hotkey or a tray
 * item: one chord, no second key, and the user pressing it while a macro runs
 * can only mean stop. StartExecution is the workspace's Run button, which sits
 * next to a Stop button - a user who wants to stop presses that, and a Run
 * press that silently stopped the run would be indistinguishable from one that
 * started a fresh one. So the shared start path still reports "execution
 * already in progress" and TestStartFlowRefusesASecondRun stays valid.
 * 
 * The stop and the start are not one atomic operation, and cannot be while
 * startFlow takes execMutex itself. What is left is the window between finding
 * the app idle and startFlow claiming it, in which a second press could load
 * its macro and then be refused by startFlow's guard - which is exactly what a
 * double-press does today, reported the same way. Nothing new is possible in
 * it: the two presses cannot both start a run, because the refusal is under the
 * same lock as the claim.
 */
export function RunMacro(id: string): $CancellablePromise<void> {
    return $Call.ByID(2292765930, id);
}

/**
 * SaveFile writes the flow data to one JSON file per macro in the app data
 * directory, records it as the last opened file, and returns the macro's id.
 * 
 * Despite what this function used to claim, it does not show a native Save File
 * dialog. That is deliberate rather than missing: the app owns its data
 * directory, and letting the user steer a macro anywhere on disk with
 * runtime.SaveFileDialog would put it outside the directory ListProjects
 * enumerates. The user picks a name; the app picks the location.
 * 
 * name is the display name the user typed, slugified into the macro's id (its
 * bare filename). currentID is the id of the macro the caller already has open,
 * empty when this graph has never been saved. Names are unique:
 * 
 *   - an empty or whitespace-only name is rejected. There is no longer a
 *     default_flow fallback - a macro saved by accident under a name nobody
 *     chose is worse than a save the user has to name;
 *   - a name whose id already exists on disk is rejected, UNLESS that id is
 *     currentID. Saving the macro you have open back over its own file is the
 *     ordinary update path and uniqueness must not stand in its way, or macros
 *     could be created but never edited.
 * 
 * Two different display names can slugify to the same id ("My Macro" and
 * "my  macro" both give "my-macro"), and the check is on the id, so the second
 * one collides rather than quietly overwriting the first.
 * 
 * Giving the open macro a new name is a rename, not a copy: the file it used to
 * live in is removed once the new one is safely on disk, so the macro list shows
 * it once under its new name instead of twice under both.
 * 
 * A save that fails costs the user nothing that was already saved: the graph is
 * written to a temporary file and renamed into place, so the macro on disk is
 * either the old one or the new one at every instant. See writeMacroFile.
 */
export function SaveFile(flowData: $models.FlowData, name: string, currentID: string): $CancellablePromise<string> {
    return $Call.ByID(4036448154, flowData, name, currentID);
}

/**
 * ShowWindow brings the main window back into view. It is what the tray's
 * "Open Keypress" item does, and what a hotkey that wants the window uses.
 * 
 * Show alone is not enough on Windows: a window that was hidden while
 * minimised comes back minimised, and one that comes back behind whatever the
 * user is now working in is easy to miss entirely.
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(2890705788);
}

/**
 * StartExecution receives the flowchart data and starts execution. It is what
 * the workspace calls to run the graph the user currently has on the canvas,
 * saved or not.
 */
export function StartExecution(flow: string): $CancellablePromise<void> {
    return $Call.ByID(3659926891, flow);
}

/**
 * StopExecution stops the ongoing execution.
 * 
 * execMutex is held for the whole of it, including across Runner.Stop's wait
 * for the walk goroutine, so that a new run cannot begin while the stopped one
 * is still winding down. That is safe only because the walk takes no lock of
 * the App's: it emits its last event and clears the execution state through an
 * atomic, and neither touches execMutex. A walk that reached for it would
 * deadlock against the wait below, which is the shape this whole lifecycle is
 * arranged to avoid.
 * 
 * Stop and not Close: this is the user pressing stop, and the next macro they
 * start has to work. ServiceShutdown is the caller that means it terminally.
 * 
 * The runner is stopped unconditionally rather than only when a run reports
 * itself in progress. "Not executing" is not the same as "no goroutine left":
 * the walk clears the flag as its last act, so a stop pressed in that instant
 * would otherwise return while the goroutine it is supposed to have joined is
 * still alive. Stop with nothing running waits, does not cancel and leaves the
 * generation alone, so the unconditional call costs a lock and a satisfied
 * WaitGroup.
 * 
 * It emits nothing. The run announces its own ending from finishRun, which is
 * the side that knows whether it was stopped or finished by itself; emitting
 * here as well reported every stop twice.
 * 
 * A closed runner is declined outright, for the reason startFlow declines one:
 * setExecuting writes twenty-odd tray menu items, and doing that once
 * ServiceShutdown has returned means writing them while the main thread destroys
 * the menu they belong to - systray.destroy() runs immediately after the
 * shutdown hook. A stop click already in flight when the user quits is exactly
 * how that happens: it races ServiceShutdown for execMutex and may well lose.
 * There is nothing left for it to do anyway - the run it meant to stop was
 * cancelled and waited for by Runner.Close.
 * 
 * Declining, not Close. This is the user pressing stop, and Close would leave
 * the runner refusing their next macro.
 */
export function StopExecution(): $CancellablePromise<void> {
    return $Call.ByID(3372805249);
}
