// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Update the App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetIsExecuting returns the current execution state.
 */
export function GetIsExecuting(): $CancellablePromise<boolean> {
    return $Call.ByID(835063317);
}

/**
 * ListProjects enumerates the saved macros in the app data directory.
 * 
 * A file that is not readable, is not valid JSON, or is JSON but not a flow is
 * skipped and logged: one stray file in the data directory must not take the
 * whole listing down with it.
 */
export function ListProjects(): $CancellablePromise<$models.ProjectSummary[] | null> {
    return $Call.ByID(2522493591);
}

/**
 * LoadLastFile loads the macro the workspace had open when it was last used,
 * returning nil without an error when there is none to load.
 * 
 * The macro is recorded in the settings file as an id, not a path, so this is
 * LoadProject by another name: the id goes through the same projectPath
 * validation, which is what keeps a hand-edited config.json from naming a file
 * outside the data directory. An id that fails it is treated as no last macro
 * at all - the app opens on an empty canvas rather than refusing to start over
 * a setting.
 * 
 * "Nothing to load" also covers the macro having been deleted since. The
 * remaining errors are a file that is there but unreadable or not a flow, which
 * the user should be told about rather than have silently swallowed.
 */
export function LoadLastFile(): $CancellablePromise<$models.FlowData | null> {
    return $Call.ByID(2612448559);
}

/**
 * LoadProject loads a single saved macro by the id ListProjects handed out.
 * 
 * The id arrives from the frontend and is turned into a path, so it is
 * validated as a bare filename first - see sanitizeProjectID.
 */
export function LoadProject(id: string): $CancellablePromise<$models.FlowData | null> {
    return $Call.ByID(76246062, id);
}

/**
 * RunMacro loads a saved macro by id and runs it, without the caller having to
 * hold the graph. It is what the tray menu and the global hotkeys use: neither
 * has a frontend to get the flowchart from, and both have to work with the
 * window closed.
 * 
 * It is bound to the frontend as well, so the projects list can run a macro
 * without opening it in the workspace first.
 */
export function RunMacro(id: string): $CancellablePromise<void> {
    return $Call.ByID(2292765930, id);
}

/**
 * SaveFile writes the flow data to one JSON file per macro in the app data
 * directory, records it as the last opened file, and returns the macro's id.
 * 
 * Despite what this function used to claim, it does not show a native Save File
 * dialog. That is deliberate rather than missing: the app owns its data
 * directory, and letting the user steer a macro anywhere on disk with
 * runtime.SaveFileDialog would put it outside the directory ListProjects
 * enumerates. The user picks a name; the app picks the location.
 * 
 * name is the display name the user typed, slugified into the macro's id (its
 * bare filename). currentID is the id of the macro the caller already has open,
 * empty when this graph has never been saved. Names are unique:
 * 
 *   - an empty or whitespace-only name is rejected. There is no longer a
 *     default_flow fallback - a macro saved by accident under a name nobody
 *     chose is worse than a save the user has to name;
 *   - a name whose id already exists on disk is rejected, UNLESS that id is
 *     currentID. Saving the macro you have open back over its own file is the
 *     ordinary update path and uniqueness must not stand in its way, or macros
 *     could be created but never edited.
 * 
 * Two different display names can slugify to the same id ("My Macro" and
 * "my  macro" both give "my-macro"), and the check is on the id, so the second
 * one collides rather than quietly overwriting the first.
 * 
 * Giving the open macro a new name is a rename, not a copy: the file it used to
 * live in is removed once the new one is safely on disk, so the macro list shows
 * it once under its new name instead of twice under both.
 * 
 * A save that fails costs the user nothing that was already saved: the graph is
 * written to a temporary file and renamed into place, so the macro on disk is
 * either the old one or the new one at every instant. See writeMacroFile.
 */
export function SaveFile(flowData: $models.FlowData, name: string, currentID: string): $CancellablePromise<string> {
    return $Call.ByID(4036448154, flowData, name, currentID);
}

/**
 * ShowWindow brings the main window back into view. It is what the tray's
 * "Open Keypress" item does, and what a hotkey that wants the window uses.
 * 
 * Show alone is not enough on Windows: a window that was hidden while
 * minimised comes back minimised, and one that comes back behind whatever the
 * user is now working in is easy to miss entirely.
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(2890705788);
}

/**
 * StartExecution receives the flowchart data and starts execution. It is what
 * the workspace calls to run the graph the user currently has on the canvas,
 * saved or not.
 */
export function StartExecution(flow: string): $CancellablePromise<void> {
    return $Call.ByID(3659926891, flow);
}

/**
 * StopExecution stops the ongoing execution.
 */
export function StopExecution(): $CancellablePromise<void> {
    return $Call.ByID(3372805249);
}
