// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Edge represents a connection between two nodes.
 */
export interface Edge {
    "id": string;
    "source": string;
    "target": string;
    "sourceHandle"?: string;
    "targetHandle"?: string;
    "type"?: string;
}

/**
 * FlowData represents the complete flow chart data structure.
 * 
 * Name is the display name the user gave the macro. It is omitted rather than
 * written empty so that flow files saved before macros were nameable still
 * round-trip unchanged; readers fall back to a name derived from the filename.
 * 
 * ID is the macro's id on disk - its bare filename, no extension. The loaders
 * fill it in so the frontend knows which macro it has open and can save back
 * over that file instead of being told the name is already taken. It is never
 * written into the file: the filename IS the id, and a second copy inside would
 * only give the two a way to disagree after a rename. SaveFile clears it before
 * encoding, and the omitempty keeps it out of the JSON either way.
 */
export interface FlowData {
    "id"?: string;
    "name"?: string;
    "nodes": Node[] | null;
    "edges": Edge[] | null;
}

/**
 * Node represents a single node in the flowchart.
 */
export interface Node {
    "id": string;
    "type": string;
    "data": { [_ in string]?: any } | null;
    "position": { [_ in string]?: number } | null;
}

/**
 * ProjectSummary describes one saved macro without loading its whole graph.
 * It is what the projects listing in the frontend renders.
 */
export interface ProjectSummary {
    /**
     * ID is the bare filename (no extension) of the macro on disk, and the
     * only handle the frontend may pass back to LoadProject.
     */
    "id": string;
    "name": string;
    "nodeCount": number;
    "edgeCount": number;

    /**
     * ModifiedAt is the file's modification time as an RFC 3339 string.
     * It is deliberately not a time.Time: Wails maps that to an untyped
     * field in the generated models, and the frontend bans `any`.
     */
    "modifiedAt": string;

    /**
     * Hotkey is the system-wide shortcut that runs this macro, empty when it
     * has none. It is stored in the settings file rather than in the macro, so
     * it is filled in here from there - see App.hotkeyFor.
     */
    "hotkey": string;
}
