// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetIsExecuting():Promise<boolean>;

export function ListProjects():Promise<Array<main.ProjectSummary>>;

export function LoadLastFile():Promise<main.FlowData>;

export function LoadProject(arg1:string):Promise<main.FlowData>;

export function SaveFile(arg1:main.FlowData,arg2:string,arg3:string):Promise<string>;

export function StartExecution(arg1:string):Promise<void>;

export function StopExecution():Promise<void>;
